name: MLIR CI

on:
  # 1. Push Event
  push:
    # Trigger the workflow when code is pushed directly to the 'develop' branch.
    branches: [develop]
  # 2. Pull Request Event
  pull_request:
    branches: [develop]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: marhvera/llvm-dev:latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake
        run: |
          mkdir -p build
          cd build
          cmake -G Ninja ..

      - name: Build project
        run: |
          cd build
          ninja -j4

      - name: Make library executable
        run: chmod +x build/tool/q2i-opt

      - name: Run MLIR conversion test via Python
        run: |
          cd test
          python3 -m unittest test_mlir_conversion -v
